version: '3.4'

services:
  compsecproject:
    image: compsecproject
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 alphabank\bencode.py "]
    ports:
      - 5678:5678
